/**
 * COURSE FILE — not part of figma/sds. See COURSE-NOTES.md.
 *
 * One Docs page per component group in Storybook: every story, then the
 * component's code (.tsx) and its CSS, read straight from src/ui. Nothing is
 * copied, so the pages follow the code after `git merge upstream/main`.
 *
 *   node scripts/course/docs-pages.mjs      writes src/stories/_course/docs/*.mdx
 *
 * Upstream's own story files are not touched: an MDX page attaches itself to
 * their stories with <Meta of={…} />.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const OUT = join(ROOT, 'src/stories/_course/docs');
const STORIES = join(ROOT, 'src/stories');

// story file → the source folders it shows
const SOURCE = {
  'compositions/Cards': ['compositions/Cards'],
  'compositions/Forms': ['compositions/Forms'],
  'layout/Flex': ['layout/Flex'],
  'layout/Grid': ['layout/Grid'],
  'layout/Section': ['layout/Section'],
  'primitives/Tab': ['primitives/Tab'],
  'primitives/IconButton': ['primitives/IconButton'],
};
const sourceFor = (key) => SOURCE[key] ?? [key];

// read every upstream story file: its title, its exports and their display names
const files = [];
for (const dir of ['primitives', 'compositions', 'layout']) {
  for (const f of readdirSync(join(STORIES, dir)).filter((x) => x.endsWith('.stories.tsx')).sort()) {
    const src = readFileSync(join(STORIES, dir, f), 'utf8');
    const title = src.match(/title:\s*"([^"]+)"/)?.[1];
    if (!title) continue;
    const stories = [...src.matchAll(/export const (\w+)[^=]*=\s*\{[\s\S]*?name:\s*"([^"]+)"/g)].map((m) => ({ id: m[1], name: m[2] }));
    files.push({ key: `${dir}/${f.replace('.stories.tsx', '')}`, file: join(STORIES, dir, f), title, stories });
  }
}

const byTitle = new Map();
for (const f of files) byTitle.set(f.title, [...(byTitle.get(f.title) ?? []), f]);

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const rel = (p) => relative(OUT, p).replaceAll('\\', '/');
const lang = (f) => (f.endsWith('.css') ? 'css' : 'tsx');
const heading = (key) => key.split('/').pop().replace(/([a-z])([A-Z])/g, '$1 $2');

let pages = 0;
for (const [title, group] of byTitle) {
  const imports = ['import { Meta, Canvas, Source } from "@storybook/blocks";'];
  const body = [];
  group.forEach((f, i) => imports.push(`import * as S${i} from "${rel(f.file)}";`));
  let n = 0;
  body.push(`<Meta of={S0} name="Code" />`, '', `# ${title.split('/').pop()}`, '');
  body.push(
    `Every story, then the code behind it: the component (\`.tsx\`) and its styles (\`.css\`), exactly as they are in the repository. The Figma library mirrors these components; its properties are the props you see here.`,
    '',
  );
  group.forEach((f, i) => {
    if (group.length > 1) body.push(`## ${heading(f.key)}`, '');
    for (const s of f.stories) body.push(`### ${s.name}`, '', `<Canvas of={S${i}.${s.id}} />`, '');
    for (const folder of sourceFor(f.key)) {
      const dir = join(ROOT, 'src/ui', folder);
      let entries = [];
      try { entries = readdirSync(dir).filter((x) => /\.(tsx|css)$/.test(x)).sort((a, b) => lang(b).localeCompare(lang(a))); } catch { continue; }
      for (const e of entries) {
        const v = `code${n++}`;
        imports.push(`import ${v} from "${rel(join(dir, e))}?raw";`);
        body.push(`${group.length > 1 ? '###' : '##'} ${lang(e) === 'css' ? 'CSS' : 'Code'} · \`src/ui/${folder}/${e}\``, '', `<Source code={${v}} language="${lang(e)}" dark />`, '');
      }
    }
  });
  const name = title.replace(/^SDS /, '').replace(/[^\w]+/g, '-');
  writeFileSync(join(OUT, `${name}.mdx`), `{/* COURSE FILE — generated by scripts/course/docs-pages.mjs. Do not edit by hand. */}\n${imports.join('\n')}\n\n${body.join('\n')}\n`);
  pages++;
}
console.log(`${pages} docs pages written to ${relative(ROOT, OUT)}`);
